#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
    echo "❌ This script must be run as root. Try again with:"
    echo "   sudo ${0}"
    exit 1
fi

pacman -Sq --needed --noconfirm zram-generator

cat > /etc/systemd/zram-generator.conf << EOF
[zram0]
zram-size = min(ram / 2, 4096)
compression-algorithm = zstd
EOF

systemctl daemon-reload
systemctl restart systemd-zram-setup@zram0.service

echo "✅ ZRAM configured"
